--- #YAML:1.0
name:               Apache-Auth-AuthMemCookie
version:            0.01
abstract:           mod_perl replacement for Apache2 authmemcookie authentication module
author:
    - Piers Harding <piers@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache2::Const:    0
    Apache2::Log:      0
    Cache::Memcached:  0
    CGI::Cookie:       0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
